### ISSUE TITLE
Class TrocoIterator - COMISSÃO

### ISSUE THREAD

**Issue by MathVasc** [MathVasc/Source-Code-Inspection#10]
Na linha 72 um laço for entra em loop infinito pois ele soma i, enquanto a condição de parada do for é decrescente

`for (int i = 6; i >= 0 && ret != null; i++) {
                if (troco.papeisMoeda[i] != null) {
                    ret = troco.papeisMoeda[i];
                    troco.papeisMoeda[i] = null;
                }
            }`

**Comment by Tnorios** [comment]
Resolvido: 
`for (int i = 6; i >= 0 && ret != null; i--)`
