### ISSUE TITLE
Class TicketMachine - COMISSÃO

### ISSUE THREAD

**Issue by MathVasc** [MathVasc/Source-Code-Inspection#12]
Na linha 40 no método getTroco é retornado null ao invés do Iterator< PapelMoeda >

`public Iterator<Integer> getTroco() {
        return null;
    }`

**Comment by Tnorios** [comment]
Resolvido: 

` public Iterator<PapelMoeda> getTroco() {
          return new Troco(saldo-valor).getIterator();
    }`
