### ISSUE TITLE
Class TrocoIterator - COMISSÃO

### ISSUE THREAD

**Issue by MathVasc** [MathVasc/Source-Code-Inspection#9]
Na linha 61 um laço for entra em loop infinito pois ele soma i, enquanto a condição de parada do for é decrescente

`for (int i = 6; i >= 0; i++) {
                if (troco.papeisMoeda[i] != null) {
                    return true;
                }
            }`

**Comment by Tnorios** [comment]
Resolvido:
`for (int i = 6; i >= 0; i--)`
